-- Tabela PESSOA
CREATE TABLE PESSOA (
    CPF CHAR(4),
    NOME VARCHAR(100),
    CONSTRAINT PK_PESSOA PRIMARY KEY (CPF)
);

-- Tabela CONTATO
CREATE TABLE CONTATO (
    CPF CHAR(4),
    CONTATO VARCHAR(10),
    CONSTRAINT PK_CONTATO PRIMARY KEY (CPF, CONTATO),
    CONSTRAINT FK_CONTATO_PESSOA FOREIGN KEY (CPF) REFERENCES PESSOA(CPF) ON DELETE CASCADE
);

-- Tabela CLIENTE
CREATE TABLE CLIENTE (
    CPF CHAR(4),
    END_CEP CHAR(8),
    END_LOGRADOURO VARCHAR(100),
    CONSTRAINT PK_CLIENTE PRIMARY KEY (CPF),
    CONSTRAINT FK_CLIENTE_PESSOA FOREIGN KEY (CPF) REFERENCES PESSOA(CPF) ON DELETE CASCADE
);

-- Tabela MEDICO
CREATE TABLE MEDICO (
    CPF CHAR(4),
    CRM VARCHAR(6),
    CONSTRAINT PK_MEDICO PRIMARY KEY (CPF),
    CONSTRAINT FK_MEDICO_PESSOA FOREIGN KEY (CPF) REFERENCES PESSOA(CPF) ON DELETE CASCADE
);

-- Tabela FUNCIONARIO
CREATE TABLE FUNCIONARIO (
    CPF CHAR(4),
    COD INT,
    CHEFE CHAR(4),
    CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (CPF),
    CONSTRAINT FK_FUNCIONARIO_PESSOA FOREIGN KEY (CPF) REFERENCES PESSOA(CPF) ON DELETE CASCADE,
    CONSTRAINT FK_FUNCIONARIO_CHEFE FOREIGN KEY (CHEFE) REFERENCES FUNCIONARIO(CPF) ON DELETE SET NULL
);

-- Tabela PRODUTO
CREATE TABLE PRODUTO (
    COD_DE_BARRA CHAR(8),
    NOME_PRODUTO VARCHAR(100),
    CONSTRAINT PK_PRODUTO PRIMARY KEY (COD_DE_BARRA)
);

-- Tabela COMPRA
CREATE TABLE COMPRA(
    CPF_CLI CHAR(4),
    CPF_FUN CHAR(4),
    COD_DE_BARRA CHAR(8),
    NOTA_FISCAL VARCHAR(8),
    CONSTRAINT PK_COMPRA PRIMARY KEY (CPF_CLI, CPF_FUN, COD_DE_BARRA, NOTA_FISCAL),
    CONSTRAINT FK_COMPRA_CLIENTE FOREIGN KEY (CPF_CLI) REFERENCES CLIENTE(CPF) ON DELETE CASCADE,
    CONSTRAINT FK_COMPRA_FUNCIONARIO FOREIGN KEY (CPF_FUN) REFERENCES FUNCIONARIO(CPF) ON DELETE CASCADE,
    CONSTRAINT FK_COMPRA_PRODUTO FOREIGN KEY (COD_DE_BARRA) REFERENCES PRODUTO(COD_DE_BARRA) ON DELETE CASCADE,
    CONSTRAINT UNIQUE_COMPRA UNIQUE (NOTA_FISCAL)
);

-- Tabela PRESCRICAO
CREATE TABLE PRESCRICAO (
    CPF_MED CHAR(4),
    DATA DATE,
    CPF_CLI CHAR(4),
    CPF_FUN CHAR(4),
    COD_DE_BARRA CHAR(8),
    NOTA_FISCAL VARCHAR(8),
    CONSTRAINT PK_PRESCRICAO PRIMARY KEY (CPF_MED, DATA),
    CONSTRAINT FK_PRESCRICAO_MEDICO FOREIGN KEY (CPF_MED) REFERENCES MEDICO(CPF) ON DELETE CASCADE,
    CONSTRAINT FK_PRESCRICAO_CLIENTE FOREIGN KEY (CPF_CLI) REFERENCES CLIENTE(CPF) ON DELETE CASCADE,
    CONSTRAINT FK_PRESCRICAO_FUNCIONARIO FOREIGN KEY (CPF_FUN) REFERENCES FUNCIONARIO(CPF) ON DELETE CASCADE,
    CONSTRAINT FK_PRESCRICAO_PRODUTO FOREIGN KEY (COD_DE_BARRA) REFERENCES PRODUTO(COD_DE_BARRA) ON DELETE CASCADE,
    CONSTRAINT FK_PRESCRICAO_PRODUTO_NF FOREIGN KEY (NOTA_FISCAL) REFERENCES COMPRA(NOTA_FISCAL) ON DELETE CASCADE,
    CONSTRAINT UNIQUE_PRESCRICAO UNIQUE (CPF_CLI, CPF_FUN, COD_DE_BARRA, NOTA_FISCAL)
);

-- Tabela FORNECEDOR
CREATE TABLE FORNECEDOR (
    CNPJ CHAR(5),
    NOME_FORNECEDOR VARCHAR(100),
    CONSTRAINT PK_FORNECEDOR PRIMARY KEY (CNPJ)
);

-- Tabela POSSUI
CREATE TABLE POSSUI (
    COD_DE_BARRA CHAR(8),
    CNPJ CHAR(5),
    CONSTRAINT PK_POSSUI PRIMARY KEY (COD_DE_BARRA, CNPJ),
    CONSTRAINT FK_POSSUI_PRODUTO FOREIGN KEY (COD_DE_BARRA) REFERENCES PRODUTO(COD_DE_BARRA) ON DELETE CASCADE,
    CONSTRAINT FK_POSSUI_FORNECEDOR FOREIGN KEY (CNPJ) REFERENCES FORNECEDOR(CNPJ) ON DELETE CASCADE
);